doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        mappings:
            Project:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Project/Entity'
                prefix: 'App\Project\Entity'
                alias: Project
            Authentication:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Authentication/Entity'
                prefix: 'App\Authentication\Entity'
                alias: Authentication
