version: '3'
services:
  education-queue-nginx:
    build:
      context: ./Docker
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - education-queue-php-fpm
    ports:
      - '8082:80'

  education-queue-php-fpm:
    build:
      context: ./Docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
    depends_on:
      - education-queue-postgres

  education-queue-php-cli:
    build:
      context: ./Docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
      - composer:/root/.composer/cache

  education-queue-postgres:
    image: postgres:13.2-alpine
    volumes:
      - education-queue-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: education
    ports:
      - '54322:5432'

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  education-queue-mailer:
    image: mailhog/mailhog
    ports:
      - '8026:8025'
      - '1026:1025'

volumes:
  education-queue-postgres:
  composer:

